# Generated by Django 3.1.4 on 2020-12-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_auto_20201218_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='instantcontent',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
