# Generated by Django 3.1.4 on 2020-12-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0004_recordeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantcontent',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recorder.recordeduser'),
        ),
    ]
