# Generated by Django 3.1.4 on 2020-12-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0005_instantcontent_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instantcontent',
            old_name='users',
            new_name='user',
        ),
    ]
